services:
  db:
    image: postgres
    container_name: postgres-gdb
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ../gdb-data:/var/lib/postgresql/data
volumes:
  pgdata:
